(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(backup-by-copying t)
 '(backup-directory-alist '(("." . "~/.emacs.d/backups")))
 '(comint-eol-on-send t)
 '(comint-input-ignoredups t)
 '(comint-move-point-for-output nil)
 '(comint-process-echoes t)
 '(comint-scroll-show-maximum-output nil)
 '(comint-scroll-to-bottom-on-output nil)
 '(company-tooltip-align-annotations t)
 '(compilation-always-kill t)
 '(compilation-message-face 'default)
 '(create-lockfiles nil)
 '(csv-separators '("," "	" ";"))
 '(debug-on-error nil)
 '(delete-old-versions t)
 '(electric-pair-mode t)
 '(epa-pinentry-mode 'loopback)
 '(epg-pinentry-mode 'loopback)
 '(eshell-hist-ignoredups t)
 '(fast-but-imprecise-scrolling t)
 '(gc-cons-threshold 268435456)
 '(indent-tabs-mode nil)
 '(indicate-buffer-boundaries 'left)
 '(indicate-empty-lines t)
 '(inferior-lisp-program "sbcl --dynamic-space-size 2048")
 '(inhibit-compacting-font-caches t t)
 '(inhibit-startup-screen t)
 '(initial-scratch-message nil)
 '(ispell-local-dictionary-alist
   '((nil "[a-zA-Z]" "[^a-zA-Z]" "[']" nil
          ("-l" "en")
          nil utf-8)
     ("english" "[a-zA-Z]" "[^a-zA-Z]" "[']" nil
      ("-l" "en")
      nil utf-8)
     ("lithuanian" "[a-zA-ZąčęėįšųūžĄČĘĖĮŠŲŪŽ]" "[^a-zA-ZąčęėįšųūžĄČĘĖĮŠŲŪŽ]" "" nil
      ("-l" "lt")
      nil utf-8)))
 '(ispell-program-name "/usr/local/bin/aspell")
 '(jit-lock-defer-time 0)
 '(js-indent-level 2)
 '(kept-new-versions 6)
 '(kept-old-versions 2)
 '(locale-coding-system 'utf-8 t)
 '(lsp-clients-typescript-log-verbosity "terse")
 '(lsp-clients-typescript-server-args '("--stdio"))
 '(lsp-clients-typescript-tls-path "typescript-language-server")
 '(lsp-headerline-breadcrumb-enable nil)
 '(lsp-keymap-prefix "C-c l")
 '(lsp-modeline-code-actions-enable nil)
 '(lsp-modeline-diagnostics-enable nil)
 '(lsp-signature-render-documentation nil)
 '(lsp-ui-doc-border "#9eacac")
 '(lsp-ui-sideline-enable nil)
 '(mode-require-final-newline t)
 '(neo-autorefresh nil)
 '(neo-smart-open t)
 '(neo-theme 'nerd)
 '(neo-vc-integration '(face char))
 '(neo-window-fixed-size nil)
 '(neo-window-width 30)
 '(next-screen-context-lines 10)
 '(ns-alternate-modifier 'super)
 '(ns-command-modifier 'meta)
 '(olivetti-body-width 120)
 '(org-bullets-bullet-list '("•"))
 '(org-ellipsis "...")
 '(org-hide-emphasis-markers t)
 '(org-hide-leading-stars t)
 '(org-src-block-faces nil)
 '(org-startup-folded 'content)
 '(org-startup-indented t)
 '(package-selected-packages
   '(prettier paredit-menu exec-path-from-shell markdown-mode nodejs-repl string-edit typescript-mode wgrep xterm-color flymake-eslint olivetti ns-auto-titlebar cider quick-peek eglot lsp paredit-everywhere slime-company slime whitespace-cleanup-mode use-package undo-tree restclient protobuf-mode paredit org-bullets neotree hungry-delete git-timemachine dictionary csv-mode company))
 '(prettier-inline-errors-flag t)
 '(query-replace-highlight t)
 '(quick-peek-add-spacer nil)
 '(quick-peek-position 'below)
 '(require-final-newline t)
 '(ring-bell-function nil)
 '(save-interprogram-paste-before-kill t)
 '(scroll-error-top-bottom t)
 '(search-highlight t)
 '(text-scale-mode-step 1.1)
 '(transient-save-history nil)
 '(typescript-indent-level 2)
 '(vc-annotate-background nil)
 '(vc-annotate-background-mode nil)
 '(vc-annotate-very-old-color nil)
 '(vc-directory-exclusion-list
   '("SCCS" "RCS" "CVS" "MCVS" ".src" ".svn" ".git" ".hg" ".bzr" "_MTN" "_darcs" "{arch}" "node_modules" "dist" "brower_components" "coverage" "build"))
 '(version-control t)
 '(visible-bell nil))

(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(default ((t (:slant normal :weight normal :height 140 :width normal :family "PragmataPro Mono"))))
 '(cursor ((t (:background "red"))))
 '(neo-file-link-face ((t (:inherit default :foreground "dark gray"))))
 '(quick-peek-background-face ((t (:inherit default :extend t))))
 '(trailing-whitespace ((t (:background "pink")))))
