;; -*- lexical-binding: t; -*-

(require 'tempo)

(defun tempo-read-insert-template (template)
  "Insert template TEMPLATE."
  (interactive (list (let* ((collection (tempo-build-collection))
                            (completion-extra-properties
                             `(:annotation-function
                               (lambda (template)
                                 (let* ((fn (alist-get template minibuffer-completion-table
                                                         nil nil #'string=)))
                                   (format "  %s" (documentation fn)))))))
                       (completing-read "Template: " collection))))
  (if-let* ((template-function (alist-get template (tempo-build-collection) nil nil #'string=)))
      (funcall template-function)
    (error "%S template not found in tempo collection." template)))

(keymap-global-set "C-x '" #'tempo-read-insert-template)

(defmacro define-tempo (template-name options documentation elements)
  (declare (indent 2))
  (let* ((mode (car options))
         (mode-prefix (string-replace "-mode" "" (symbol-name mode)))
         (tag-list (intern (concat mode-prefix "-tempo-template-tags")))
         (mode-hook (intern (concat (symbol-name mode) "-hook")))
         (use-hook (intern (concat "use-" (symbol-name tag-list) "-templates")))
         (abbrev-table (intern (concat (symbol-name mode)  "-abbrev-table")))
         (full-template-name
          (string-join (seq-filter #'identity (list mode-prefix (symbol-name template-name))) "-")))
    `(progn
       ,@(unless (boundp tag-list)
           `((defvar ,tag-list nil
               ,(format "Holds tempo templates for %s." tag-list mode))
             (defun ,use-hook ()
               ,(format "Autogenerated function to enable `%s' tempo templates in `%s'." tag-list mode)
               (tempo-use-tag-list ',tag-list))
             (add-hook ',mode-hook #',use-hook)))
       (tempo-define-template ,full-template-name
                              ,elements
                              ,(symbol-name template-name)
                              ,documentation
                              ',tag-list)
       (define-abbrev ,abbrev-table ,(symbol-name template-name) ""
         ',(intern (concat "tempo-template-" full-template-name))))))

(define-tempo react-component (typescript-ts-base-mode)
  "interface ComponentProps and const Component: FC<ComponentProps> = ..."
  '("interface " (r "Component name: " name) "Props {}"
    n n
    "const " (s name) ": FC<" (s name) "Props> = () => {" n
    > "return " p "null;" n
    > "};"))

(define-tempo react-component (js-base-mode)
  "function Component(props) { ... }"
  '("function " (r "Component name: " name) "(props) {" n
    > "return " p "null;" n
    "}" >)
  "fc")

(define-tempo lambda (emacs-lisp-mode)
  "(lambda () ...)"
  '("(lambda (" p "))"))

(define-tempo html (sgml-mode)
  "Insert basic HTML5 document."
  '("<!doctype html>" n
    > "<html lang=\"en\">" n
    > "<head>" n
    > "<meta charset=\"UTF-8\" />" n
    > "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />" n
    > "<title>Document</title>" n
    > "</head>" > n
    > "<body>" n
    > p n
    "</body>" > n
    "</html>" > n))

(define-tempo post-header (org-mode)
  "Blog post header."
  '("#+TITLE: " p n
    "#+SUBTITLE: " n
    "#+OPTIONS: num:nil toc:nil" n
    "#+PROPERTY: header-args :exports both :results scalar :noweb yes" n n))

(provide 'setup-tempo)
